#Experiment 13 :- Data Binning and Data Formation Using Python
##NAME: Gayatri Bhosale
##PRN:25070123033

In [2]:
import pandas as pd
import numpy as np

data ={
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15]
}
df = pd.DataFrame(data)
print("Dataset")
print(df)

Dataset
      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [3]:
#Data Binnning
bins1 = [0,10000,30000,60000]
labels1 = ['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [6]:
#Binning Units Sold
bins2 = [0,30,60,100]
labels2 = ['Low sales','Moderate Sales','High Sales']
df['Sales Category'] = pd.cut(df['Units_Sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category  Sales Category
0      Laptop  55000          25           High       Low sales
1      Mobile  20000          60         Medium  Moderate Sales
2      Tablet  30000          35         Medium  Moderate Sales
3  Headphones   2000          80            Low      High Sales
4  Smartwatch   8000          50            Low  Moderate Sales
5      Camera  45000          15           High       Low sales

In [12]:
#Data Formating
#Convert Data Type
print(df.dtypes)
df['Units_Sold']=df['Units_Sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales Category    category
dtype: object

In [13]:
#Convert Text to Uppercase
df['Product']=df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category  Sales Category
0      LAPTOP  55000        25.0           High       Low sales
1      MOBILE  20000        60.0         Medium  Moderate Sales
2      TABLET  30000        35.0         Medium  Moderate Sales
3  HEADPHONES   2000        80.0            Low      High Sales
4  SMARTWATCH   8000        50.0            Low  Moderate Sales
5      CAMERA  45000        15.0           High       Low sales

In [15]:
#Rounding Values
df['Price']=df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category  Sales Category
0      LAPTOP  55000        25.0           High       Low sales
1      MOBILE  20000        60.0         Medium  Moderate Sales
2      TABLET  30000        35.0         Medium  Moderate Sales
3  HEADPHONES   2000        80.0            Low      High Sales
4  SMARTWATCH   8000        50.0            Low  Moderate Sales
5      CAMERA  45000        15.0           High       Low sales

In [17]:
 #Additional Operations
 #Sort Data
 sorted_df = df.sort_values(by='Price',ascending=False)
 print(sorted_df)

      Product  Price  Units_Sold Price_Category  Sales Category
0      LAPTOP  55000        25.0           High       Low sales
5      CAMERA  45000        15.0           High       Low sales
2      TABLET  30000        35.0         Medium  Moderate Sales
1      MOBILE  20000        60.0         Medium  Moderate Sales
4  SMARTWATCH   8000        50.0            Low  Moderate Sales
3  HEADPHONES   2000        80.0            Low      High Sales

In [19]:
#Display Uniques Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [38]:
#DataSet: Food Delivery
import pandas as pd
import numpy as np
data={
    'Order_ID':['01','02','03','04','05','06','07','08'],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,25,60,35,20,50,28],
    'Distance_Km':[5,8,3,10,6,2,9,4]
}
df=pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_Km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [40]:
#Binning Order Value
bins1 = [0,200,400,700]
labels1 = ['Low Order','Medium Order','High Order']
df['Order Category'] = pd.cut(df['Order_Value'],bins=bins1,labels=labels1)
df

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order Category
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

In [29]:
#Binning Delivery Time
bins2 = [0,30,45,70]
lables2=['Fast','Normal','Slow']
df['Delivery_Speed'] = pd.cut(df['Delivery_Time'],bins=bins2,labels=lables2)
df

  Order_ID  Orde_Value  Delivery_Time  Distance_Km Delivery_Speed
0       01         250             30            5           Fast
1       02         450             45            8         Normal
2       03         120             25            3           Fast
3       04         600             60           10           Slow
4       05         300             35            6         Normal
5       06         150             20            2           Fast
6       07         500             50            9           Slow
7       08         220             28            4           Fast

In [42]:
#Data Formating Examples
#Convert Distance To Float
df['Distance_Km']=df['Distance_Km'].astype(float)
df.dtypes
df

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order Category
0       01          250             30          5.0   Medium Order
1       02          450             45          8.0     High Order
2       03          120             25          3.0      Low Order
3       04          600             60         10.0     High Order
4       05          300             35          6.0   Medium Order
5       06          150             20          2.0      Low Order
6       07          500             50          9.0     High Order
7       08          220             28          4.0   Medium Order

In [43]:
#Convert Order_ID to Uppercase
df['Order_ID']=df['Order_ID'].str.upper()
df

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order Category
0       01          250             30          5.0   Medium Order
1       02          450             45          8.0     High Order
2       03          120             25          3.0      Low Order
3       04          600             60         10.0     High Order
4       05          300             35          6.0   Medium Order
5       06          150             20          2.0      Low Order
6       07          500             50          9.0     High Order
7       08          220             28          4.0   Medium Order

In [44]:
#Check Data Types
print(df.dtypes)

Order_ID            object
Order_Value          int64
Delivery_Time        int64
Distance_Km        float64
Order Category    category
dtype: object

In [46]:
#Unique Categories
print(df['Order Category'].unique())
df

['Medium Order', 'High Order', 'Low Order']
Categories (3, object): ['Low Order' < 'Medium Order' < 'High Order']

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order Category
0       01          250             30          5.0   Medium Order
1       02          450             45          8.0     High Order
2       03          120             25          3.0      Low Order
3       04          600             60         10.0     High Order
4       05          300             35          6.0   Medium Order
5       06          150             20          2.0      Low Order
6       07          500             50          9.0     High Order
7       08          220             28          4.0   Medium Order

In [49]:
#Count Categories
print(df['Order Category'].value_counts())
df

Order Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order Category
0       01          250             30          5.0   Medium Order
1       02          450             45          8.0     High Order
2       03          120             25          3.0      Low Order
3       04          600             60         10.0     High Order
4       05          300             35          6.0   Medium Order
5       06          150             20          2.0      Low Order
6       07          500             50          9.0     High Order
7       08          220             28          4.0   Medium Order

In [50]:
#Sorting
print(df.sort_values(by='Order_Value'))
df

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order Category
2       03          120             25          3.0      Low Order
5       06          150             20          2.0      Low Order
7       08          220             28          4.0   Medium Order
0       01          250             30          5.0   Medium Order
4       05          300             35          6.0   Medium Order
1       02          450             45          8.0     High Order
6       07          500             50          9.0     High Order
3       04          600             60         10.0     High Order

  Order_ID  Order_Value  Delivery_Time  Distance_Km Order Category
0       01          250             30          5.0   Medium Order
1       02          450             45          8.0     High Order
2       03          120             25          3.0      Low Order
3       04          600             60         10.0     High Order
4       05          300             35          6.0   Medium Order
5       06          150             20          2.0      Low Order
6       07          500             50          9.0     High Order
7       08          220             28          4.0   Medium Order