# Unit 3 Data Wrangling
# Experiment 12: To perform preprocessing on a Dealing with Missing Values
## Name: Gayatri Bhosale
### PRN: 25070123033

In [1]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [2]:
 df1.isna() #Boolean Function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [3]:
df1.isna().sum() # columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [5]:
df1.dropna() #NaN Rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [6]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [7]:
df1.fillna(df1.mean()) # Mean value of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [14]:
# Preprocessing of Dataset-1
import pandas as pd
data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha","Rohan","Meera","Karan","Anil"],
    "Age": [20, "-", 19, 21, "22"],
    "Marks": [85,90,"-",88,76],
    "Department": ["CSE","ENTC","CSE","IT","CSE"],
    "Admission_Date":["01-06-2023","03-06-2023","05-06-2023","07-06-2023","10/06/2023"]
}
df = pd.DataFrame(data)
print(df)

# Save as CSV
df.to_csv("student_data.csv", index=False)

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90       ENTC     03-06-2023
2      103  Meera  19     -        CSE     05-06-2023
3      104  Karan  21    88         IT     07-06-2023
4      105   Anil  22    76        CSE     10/06/2023

In [15]:
#Step 2: Replace '-' wiith NaN To Mark missing values
df.replace("-",np.nan,inplace=True)
df

/tmp/ipykernel_403/189416852.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-",np.nan,inplace=True)

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0       ENTC     03-06-2023
2      103  Meera   19    NaN        CSE     05-06-2023
3      104  Karan   21   88.0         IT     07-06-2023
4      105   Anil   22   76.0        CSE     10/06/2023

In [18]:
#Convert Columns to numeric where needed
df["Age"]=pd.to_numeric(df["Age"], errors='coerce')
df["Marks"]=pd.to_numeric(df["Marks"],errors='coerce')
df

''' When converting data (like strings + datetime),
if some values are invalid or cannot

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0       ENTC     03-06-2023
2      103  Meera  19.0    NaN        CSE     05-06-2023
3      104  Karan  21.0   88.0         IT     07-06-2023
4      105   Anil  22.0   76.0        CSE     10/06/2023

In [19]:
#Step 3: Check missing values
print("\nMissing Values:")
print(df.isna().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [20]:
#Fill Missing Age With Mean
df["Age"].fillna(df["Age"].mean(),inplace=True)
df

/tmp/ipykernel_403/2052866963.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan  20.5   90.0       ENTC     03-06-2023
2      103  Meera  19.0    NaN        CSE     05-06-2023
3      104  Karan  21.0   88.0         IT     07-06-2023
4      105   Anil  22.0   76.0        CSE     10/06/2023

In [21]:
#Fill Missing Marks With Median
df["Marks"].fillna(df["Marks"].median(),inplace=True)
df

/tmp/ipykernel_403/4173389280.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan  20.5   90.0       ENTC     03-06-2023
2      103  Meera  19.0   86.5        CSE     05-06-2023
3      104  Karan  21.0   88.0         IT     07-06-2023
4      105   Anil  22.0   76.0        CSE     10/06/2023

In [22]:
#Step 5: Fix inconsistent text formating
df["Department"]=df["Department"].str.upper()
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan  20.5   90.0       ENTC     03-06-2023
2      103  Meera  19.0   86.5        CSE     05-06-2023
3      104  Karan  21.0   88.0         IT     07-06-2023
4      105   Anil  22.0   76.0        CSE     10/06/2023

In [25]:
#Step 6: Convert Admission_Date to standard datetime format
df["Admission_Date"]=pd.to_datetime(df["Admission_Date"],errors='coerce')
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     2023-01-06
1      102  Rohan  20.5   90.0       ENTC     2023-03-06
2      103  Meera  19.0   86.5        CSE     2023-05-06
3      104  Karan  21.0   88.0         IT     2023-07-06
4      105   Anil  22.0   76.0        CSE            NaT

In [26]:
#Step 7:Save cleaned dataset
df.to_csv('cleaned_dataset.csv', index=False)

print("ncleaned CSV file saved_student_data")

ncleaned CSV file saved_student_data

# Preprocessing of Dataset-2
## Checking For Missing Values

In [28]:
#Working with missing values On DataSet-2
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [29]:
df.isna().sum() #Attributes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [38]:
#Implementing the missing Value
#1. Luggage Room
df['Luggage.room']=df['Luggage.room'].fillna(value=df['Luggage.room'].mean())
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [39]:
#2. Rear.seat.room
df['Rear.seat.room']=df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].mean())
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [41]:
#3 Airbags
df['AirBags']=df['AirBags'].fillna(value=df['AirBags'].mode().values[0])
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [44]:
#Save Cleaned DataSet
df.to_csv('updated_cars93.csv', index=False)