#Experiment No. 10
## Create a Dataset ad Load Dataset
### Name: Gayatri Bhosale
### PRN: 25070123033

In [ ]:
#Dataset Creation
import pandas as pd

data={
    "Roll_no":[101,102,103,104,105],
    "Gender":["Female","Male","Female","Male","Male"],
    "Department":["CSE","Mechanical","ENTC","IT","ENTC"],
    "CGPA":[8.2,7.5,9.1,6.8,8.7]
}

df=pd.DataFrame(data)

df.to_csv("student.csv" , index=False)
print(df)

   Roll_no  Gender  Department  CGPA
0      101  Female         CSE   8.2
1      102    Male  Mechanical   7.5
2      103  Female        ENTC   9.1
3      104    Male          IT   6.8
4      105    Male        ENTC   8.7

In [ ]:
df["Year"]=["First Year","Second Year","Final Year","Third Year","second Year"]
df

   Roll_no  Gender  Department  CGPA         Year
0      101  Female         CSE   8.2   First Year
1      102    Male  Mechanical   7.5  Second Year
2      103  Female        ENTC   9.1   Final Year
3      104    Male          IT   6.8   Third Year
4      105    Male        ENTC   8.7  second Year

In [ ]:
df.shape

(5, 5)

In [ ]:
df.size

25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_no     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   Year        5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [ ]:
df.describe()

          Roll_no     CGPA
count    5.000000  5.00000
mean   103.000000  8.06000
std      1.581139  0.92358
min    101.000000  6.80000
25%    102.000000  7.50000
50%    103.000000  8.20000
75%    104.000000  8.70000
max    105.000000  9.10000

In [ ]:
#access information of the column department
df["Department"]

0           CSE
1    Mechanical
2          ENTC
3            IT
4          ENTC
Name: Department, dtype: object

In [ ]:
#access information of PRN 103
df.loc[2]

Roll_no              103
Gender            Female
Department          ENTC
CGPA                 9.1
Year          Final Year
Name: 2, dtype: object

In [ ]:
#find out data type of each column
df.dtypes

Roll_no         int64
Gender         object
Department     object
CGPA          float64
Year           object
dtype: object

In [ ]:
#perform mean,median,mode operations
mean1 = df["CGPA"].mean()
print(mean1)

median1 = df["CGPA"].median()
print(median1)

mode1 = df["CGPA"].mode()
print(mode1)

8.059999999999999
8.2
0    6.8
1    7.5
2    8.2
3    8.7
4    9.1
Name: CGPA, dtype: float64

In [ ]:
#insert a new column Grade
grade = ["A","B","A","C","B"]
df["Grade"] = grade
df

   Roll_no  Gender  Department  CGPA         Year Grade
0      101  Female         CSE   8.2   First Year     A
1      102    Male  Mechanical   7.5  Second Year     B
2      103  Female        ENTC   9.1   Final Year     A
3      104    Male          IT   6.8   Third Year     C
4      105    Male        ENTC   8.7  second Year     B

In [ ]:
#Delet Gender Column
df.drop("Gender",axis=1)

   Roll_no  Department  CGPA         Year Grade
0      101         CSE   8.2   First Year     A
1      102  Mechanical   7.5  Second Year     B
2      103        ENTC   9.1   Final Year     A
3      104          IT   6.8   Third Year     C
4      105        ENTC   8.7  second Year     B

In [ ]:
#CGPA of topper
max1=df["CGPA"].max()
max1

9.1

In [ ]:
#CGPA of PRN 105
df.loc[4,"CGPA"]

np.float64(8.7)

In [ ]:
#Upload The Dataset
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.size

930

In [ ]:
df.shape

(93, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.dtypes

Manufacturer       object
Model              object
Type               object
Price             float64
MPG.city            int64
AirBags            object
Horsepower          int64
Passengers          int64
Rear.seat.room    float64
Luggage.room      float64
dtype: object